**Practice Questions related to Numpy Basics**

Question 1: Implement all the discussed examples.

Example 1: Creating ndarrays

In [1]:
import numpy as np

data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [2]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
arr2.ndim

2

In [4]:
arr2.shape

(2, 4)

In [5]:
arr1.dtype

dtype('float64')

In [6]:
arr2.dtype

dtype('int64')

In [7]:
arr3 = np.array([1, 2, 3], dtype=np.float64)
arr3

array([1., 2., 3.])

In [8]:
arr4 = np.array([1, 2, 3], dtype=np.int32)
arr4

array([1, 2, 3], dtype=int32)

In [9]:
arr3.dtype

dtype('float64')

In [10]:
arr4.dtype

dtype('int32')

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
np.empty((2, 3, 2))

array([[[1.19506577e-311, 7.24116756e-315],
        [0.00000000e+000, 0.00000000e+000],
        [3.44902066e-307, 5.74084271e+169]],

       [[7.48375038e-091, 4.74968728e+174],
        [1.29095952e+160, 6.34416145e-066],
        [3.99910963e+252, 8.35597381e-309]]])

In [14]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Example 2: Type Conversion for ndarrays

In [15]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [16]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [17]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [18]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [19]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.bytes_)

In [20]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [21]:
int_array = np.arange(10)

In [22]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [23]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

Example 3: Operations between Arrays and Scalars

In [25]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [26]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [27]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [29]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

Example 4: Basic indexing and slicing

In [30]:
arr = np.arange(10)

In [31]:
arr[5]

np.int64(5)

In [32]:
arr[5:8]

array([5, 6, 7])

In [33]:
arr[5:8 ]= 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [34]:
arr_slice = arr[5:8]
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [35]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [36]:
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2d[2]

array([7, 8, 9])

In [37]:
array2d[0][2]

np.int64(3)

In [38]:
array2d[0, 2]

np.int64(3)

In [39]:
array3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
array3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
old_value = array3d[0].copy()
array3d[0] = 42
array3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [41]:
array3d[0] = old_value
array3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [42]:
array3d[1,0]

array([7, 8, 9])

Example 5: Indexing with slicing

In [43]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [44]:
array2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
array2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [46]:
array2d[2, :1]

array([7])

In [47]:
array2d[1, :2]

array([4, 5])

In [48]:
array2d[2, :1]

array([7])

In [49]:
array2d[:, :1]

array([[1],
       [4],
       [7]])

In [50]:
array2d[:2, 1:] = 0

Example 6: Broadcasting

In [51]:
arr = np.arange(5)

In [52]:
arr * 4

array([ 0,  4,  8, 12, 16])

In [53]:
arr = np.random.randn(4, 3)
arr.mean(0)

array([-0.16480489, -0.58770537,  0.56088667])

In [54]:
demeaned = arr - arr.mean(0)
demeaned

array([[ 0.36718385,  1.47280304, -1.56943247],
       [ 0.07688404, -0.86475212, -0.21025317],
       [ 0.03635661, -0.33481175, -0.03597041],
       [-0.48042451, -0.27323917,  1.81565605]])

In [55]:
demeaned.mean(0)

array([1.38777878e-17, 8.32667268e-17, 0.00000000e+00])

In [56]:
row_means = arr.mean(1)
row_means.reshape((4, 1))

array([[ 0.02631028],
       [-0.39658162],
       [-0.17534971],
       [ 0.29012292]])

In [57]:
demeaned = arr - row_means.reshape((4, 1))
demeaned.mean(1)

array([0.00000000e+00, 3.70074342e-17, 7.40148683e-17, 0.00000000e+00])

Example 7: Set Array Values by Broadcasting

In [58]:
arr = np.zeros((4, 3))
arr[:] = 5
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [59]:
col = np.array([1.28, -0.42, 0.44, 1.6])
arr[:] = col[:, np.newaxis]
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [60]:
arr[:2] = [[-1.37], [0.509]]
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

Example 8: Boolean Indexing

In [61]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe',
'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [62]:
data

array([[ 0.30801778, -0.22881074, -0.71679396,  1.34993068],
       [ 0.02917405,  0.25124662,  0.75559729, -0.80122933],
       [-0.56251239, -0.28923145, -1.18959015,  0.77453771],
       [-1.05094574, -0.4872028 , -0.26524014,  1.95812631],
       [-1.11161184,  0.14008351,  1.89554879, -1.57079914],
       [-1.60150104, -0.8782457 , -0.46109293, -0.65436686],
       [ 1.60461462, -1.02647208,  0.23708302, -0.46893863]])

In [63]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [64]:
data[names == 'Bob']

array([[ 0.30801778, -0.22881074, -0.71679396,  1.34993068],
       [-1.05094574, -0.4872028 , -0.26524014,  1.95812631]])

In [65]:
data[names == 'Bob', 2:]

array([[-0.71679396,  1.34993068],
       [-0.26524014,  1.95812631]])

In [66]:
data[names == 'Bob', 3]

array([1.34993068, 1.95812631])

In [67]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [68]:
data[~(names == 'Bob')]

array([[ 0.02917405,  0.25124662,  0.75559729, -0.80122933],
       [-0.56251239, -0.28923145, -1.18959015,  0.77453771],
       [-1.11161184,  0.14008351,  1.89554879, -1.57079914],
       [-1.60150104, -0.8782457 , -0.46109293, -0.65436686],
       [ 1.60461462, -1.02647208,  0.23708302, -0.46893863]])

In [69]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [70]:
data[mask]

array([[ 0.30801778, -0.22881074, -0.71679396,  1.34993068],
       [-0.56251239, -0.28923145, -1.18959015,  0.77453771],
       [-1.05094574, -0.4872028 , -0.26524014,  1.95812631],
       [-1.11161184,  0.14008351,  1.89554879, -1.57079914]])

In [71]:
data[data < 0] = 0
data

array([[0.30801778, 0.        , 0.        , 1.34993068],
       [0.02917405, 0.25124662, 0.75559729, 0.        ],
       [0.        , 0.        , 0.        , 0.77453771],
       [0.        , 0.        , 0.        , 1.95812631],
       [0.        , 0.14008351, 1.89554879, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [1.60461462, 0.        , 0.23708302, 0.        ]])

In [72]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.02917405, 0.25124662, 0.75559729, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [1.60461462, 0.        , 0.23708302, 0.        ]])

Example 9: Fancy Indexing

In [73]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [74]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [75]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [76]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [77]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [78]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [79]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

Example 10: Transposing and Swapping Axes

In [80]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [81]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [82]:
arr = np.random.randn(6, 3)

In [83]:
np.dot(arr.T, arr)

array([[ 0.70296831, -0.94956702, -0.78927466],
       [-0.94956702,  3.6739783 , -1.0715506 ],
       [-0.78927466, -1.0715506 ,  6.02711658]])

In [84]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [85]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [86]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [87]:
A = np.random.randn(4,3)

B = np.sum(A, axis = 1, keepdims = True) 

B.shape

(4, 1)

Example 11: Reshaping Arrays

In [88]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [89]:
arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [90]:
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [91]:
arr = np.arange(15)

In [92]:
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [93]:
other_arr = np.ones((3, 5))
other_arr.shape

(3, 5)

In [94]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [95]:
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [96]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [97]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Example 12: Concatinating and splitting arrays

In [98]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

In [99]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [100]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [101]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [102]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [103]:
from numpy.random import randn
arr = randn(5, 2)
arr

array([[-0.99177763, -1.12385624],
       [ 0.31140293, -0.92402057],
       [ 0.10630675,  0.68539398],
       [ 1.89100253,  0.3019261 ],
       [-0.81857018, -0.36171441]])

In [104]:
first, second, third = np.split(arr, [1, 3])
first

array([[-0.99177763, -1.12385624]])

In [105]:
second

array([[ 0.31140293, -0.92402057],
       [ 0.10630675,  0.68539398]])

In [106]:
third

array([[ 1.89100253,  0.3019261 ],
       [-0.81857018, -0.36171441]])

Example 13: Universal Functions: Fast Element-wise Array Functions

In [107]:
arr = np.arange(10)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [108]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [109]:
x = randn(8)
x

array([-0.71499441, -0.20182396, -0.23926845, -1.16399762,  0.1265012 ,
       -1.64203654, -0.2569156 ,  1.5540129 ])

In [110]:
y = randn(8)
y

array([-1.63035707, -1.52340657,  0.91957719,  1.71227607, -0.3591645 ,
       -0.04251392, -0.21544452,  0.57908721])

In [111]:
np.maximum(x, y) # element-wise maximum

array([-0.71499441, -0.20182396,  0.91957719,  1.71227607,  0.1265012 ,
       -0.04251392, -0.21544452,  1.5540129 ])

In [112]:
arr = randn(7) * 5
np.modf(arr)

(array([ 0.23923342, -0.92954096,  0.02723449,  0.04245622, -0.30552604,
         0.33588825,  0.28655093]),
 array([ 8., -6.,  2.,  4., -1.,  2., 10.]))

In [113]:
arr = np.arange(10)
np.add.reduce(arr)

np.int64(45)

In [114]:
arr.sum()

np.int64(45)

In [115]:
arr = randn(5, 5)
arr[::2].sort(1) # sort a few rows
arr[:, :-1] < arr[:, 1:]

array([[ True,  True,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True,  True],
       [ True, False,  True, False],
       [ True,  True,  True,  True]])

In [116]:
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1)

array([ True, False,  True, False,  True])

In [117]:
arr = np.arange(15).reshape((3, 5))
np.add.accumulate(arr, axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [118]:
arr = np.arange(3).repeat([1, 2, 2])
arr

array([0, 1, 1, 2, 2])

In [119]:
np.multiply.outer(arr, np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [120]:
result = np.subtract.outer(randn(3, 4), randn(5))
result.shape

(3, 4, 5)

In [121]:
arr = np.arange(10)
np.add.reduceat(arr, [0, 5, 8])

array([10, 18, 17])

In [122]:
arr = np.multiply.outer(np.arange(4), np.arange(5))
arr

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [123]:
np.add.reduceat(arr, [0, 2, 4], axis=1)

array([[ 0,  0,  0],
       [ 1,  5,  4],
       [ 2, 10,  8],
       [ 3, 15, 12]])

Example 14: Mathematical and Statistical Methods

In [124]:
arr = np.random.randn(5,4)
arr.mean()

np.float64(0.0030276272530006866)

In [125]:
np.mean(arr, axis=1)

array([ 0.06410507,  0.02921586,  0.54013727, -0.62081418,  0.00249412])

In [126]:
arr.sum()

np.float64(0.06055254506001373)

In [127]:
arr.mean(axis = 1)

array([ 0.06410507,  0.02921586,  0.54013727, -0.62081418,  0.00249412])

In [128]:
arr.sum(0)

array([ 1.96360722, -0.85507883, -0.69091548, -0.35706036])

In [129]:
arr.cumsum(0)

array([[-5.07303324e-04, -8.35812093e-02,  7.42844511e-01,
        -4.02335726e-01],
       [ 1.85764762e+00,  3.60071466e-02, -2.28121404e-01,
        -1.29224965e+00],
       [ 3.34578492e+00, -7.36670419e-01,  2.56751091e-01,
        -3.32032799e-01],
       [ 3.69965243e+00, -1.51397279e+00, -3.21600245e-01,
        -1.81350333e+00],
       [ 1.96360722e+00, -8.55078833e-01, -6.90915476e-01,
        -3.57060364e-01]])

In [130]:
arr.cumprod(1)

array([[-5.07303324e-04,  4.24010253e-05,  3.14973689e-05,
        -1.26725168e-05],
       [ 1.85815492e+00,  2.22213692e-01, -2.15761921e-01,
         1.92009537e-01],
       [ 1.48813730e+00, -1.14985031e+00, -5.57530787e-01,
        -5.35350456e-01],
       [ 3.53867509e-01, -2.75062055e-01,  1.59082507e-01,
        -2.35676045e-01],
       [-1.73604521e+00, -1.14386970e+00,  4.22448503e-01,
         6.15272149e-01]])

Example 15: Sorting

In [131]:
arr = randn(8)
arr

array([-0.01953512,  1.13861835,  0.33438576,  0.90615236, -0.46387123,
       -0.46456405,  0.05266832,  1.43792249])

In [132]:
arr.sort()
arr

array([-0.46456405, -0.46387123, -0.01953512,  0.05266832,  0.33438576,
        0.90615236,  1.13861835,  1.43792249])

In [133]:
arr = randn(5,3)
arr

array([[-0.56702832,  0.70174599, -0.41607784],
       [-0.89745976, -0.48023099,  0.69332337],
       [-0.31168178, -1.55046971,  1.49019227],
       [ 0.77346791, -0.282822  ,  0.9810547 ],
       [-0.67040302, -1.58948185,  0.88583919]])

In [134]:
arr.sort(1)
arr

array([[-0.56702832, -0.41607784,  0.70174599],
       [-0.89745976, -0.48023099,  0.69332337],
       [-1.55046971, -0.31168178,  1.49019227],
       [-0.282822  ,  0.77346791,  0.9810547 ],
       [-1.58948185, -0.67040302,  0.88583919]])

In [137]:
large_arr = randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))]

np.float64(-1.5615267817560665)

Example 16: Unique and Other Set Logic

In [138]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [139]:
sorted(set(names))

[np.str_('Bob'), np.str_('Joe'), np.str_('Will')]

In [140]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.isin(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

Example 17: Linear Algebra

In [141]:
x = np.array([[1.,2.,3.],[4.,5.,6.]])
y = np.array([[6.,23.],[-1,7.],[8,9.]])
x.dot

<function ndarray.dot>

In [142]:
np.dot(x,np.ones(3))

array([ 6., 15.])

In [143]:
from numpy.linalg import inv, qr
X = randn(5, 5)
mat = X.T.dot(X)
inv(mat)

array([[  67.51877268, -120.10139204,   83.09157142,  -43.17515526,
         -31.01307844],
       [-120.10139204,  214.71914355, -148.40106072,   77.52879758,
          54.91274925],
       [  83.09157142, -148.40106072,  102.75297188,  -53.57937601,
         -37.9732589 ],
       [ -43.17515526,   77.52879758,  -53.57937601,   28.35359373,
          19.53412459],
       [ -31.01307844,   54.91274925,  -37.9732589 ,   19.53412459,
          14.54932532]])

In [144]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -1.44100597e-13,  1.14547070e-13,
        -4.42078651e-14, -1.49288363e-14],
       [-4.59335422e-14,  1.00000000e+00,  6.70235586e-14,
         3.52411305e-15, -9.59281832e-15],
       [-7.13948524e-14,  3.66429993e-14,  1.00000000e+00,
         3.62802819e-14,  1.56759445e-14],
       [ 5.29752650e-14, -1.12800422e-13,  1.75223488e-14,
         1.00000000e+00, -3.47336395e-14],
       [ 3.41105914e-14, -8.30753453e-14, -1.62097180e-14,
         1.14056630e-14,  1.00000000e+00]])

In [145]:
q, r = qr(mat)
r

array([[-8.96270286, -0.6697237 ,  4.57411709,  0.61310456, -5.49091692],
       [ 0.        , -5.98317175, -5.06472367,  4.57611245,  3.23496559],
       [ 0.        ,  0.        , -3.8686076 , -4.68936642, -3.83567942],
       [ 0.        ,  0.        ,  0.        , -0.72099452,  1.01557192],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.01289657]])

Example 18: Random Number Generation

In [146]:
samples = np.random.normal(size=(4, 4))
samples

array([[-0.21316627, -0.02191644, -0.02552165, -0.00982983],
       [ 0.16425853,  2.25626849,  1.38194443, -0.47092521],
       [ 0.89080903,  0.10966645,  0.70171494,  1.1212536 ],
       [ 0.06255764,  0.1788905 ,  1.09526223, -0.44261419]])

Example 19: File Input and Output Arrays

In [147]:
arr = np.arange(10)
np.save('some_array', arr)

In [148]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:
np.savez('array_archive.npz', a=arr, b=arr)

In [150]:
arch = np.load('array_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Example 20: Saving and Loading Text Files

In [152]:
arr = np.loadtxt('array_ex.txt', delimiter=',')
arr

array([[ 0.580052,  0.18673 ,  1.040717,  1.134411],
       [ 0.194163, -0.636917, -0.938659,  0.124094],
       [-0.12641 ,  0.268607, -0.695724,  0.047428],
       [-1.484413,  0.004176, -0.744203,  0.005487],
       [ 2.302869,  0.200131,  1.670238, -1.88109 ],
       [-0.19323 ,  1.047233,  0.482803,  0.960334]])