BASICS OF NUMPY

In [80]:
import numpy as np

x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
w = np.array([0.5,0.2,0.3,0.6])

h = np.dot(x,w)
h

array([ 4.2, 10.6, 17. ])

In [81]:
import numpy as np
a = np.array([[1,2,3,4],[1,2,3,4]])
a

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [82]:
a.ndim

2

In [83]:
a.dtype

dtype('int64')

In [84]:
b = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
np.shape(b)

(2, 3, 4)

In [85]:
c = np.array([[[1,2],[1,2]],[[3,4],[3,4]],[[6,7],[6,7]]])
np.shape(c)

(3, 2, 2)

In [86]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [87]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [88]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [89]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [90]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
np.arange(1,10).reshape(3,3) #nine elements can be represented as a 3x3 matrix.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
np.arange(1,13).reshape(4,-1) #reshaping converts a 1D array to 2D array
# here if we write -1 then numpy will automatically detect the size of the matrix.

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

.reshape(-1,4)
former represents the column and latter represents the row.

In [93]:
np.arange(1,13).reshape(-1,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

some basic operations

In [94]:
e = np.array([1])
f = np.array([2,3,4,5])

g = e-f
g

array([-1, -2, -3, -4])

In [95]:
i = e + f
i

array([3, 4, 5, 6])

In [96]:
j = e*f
j

array([2, 3, 4, 5])

In [97]:
k = e//f
k

array([0, 0, 0, 0])

In [98]:
l = e**f
l

array([1, 1, 1, 1])

In [99]:
e<2

array([ True])

In [100]:
print(f.sum())

14


In [101]:
print(f.min())

2


In [102]:
print(f.max())

5


In [103]:
print(np.exp(4))

54.598150033144236


In [104]:
print(f.sum(axis = 0))

14


CUMSUM

In [105]:
k = np.array([[1,2,4,5],[6,7,8,9]])
print(k.cumsum(axis = 1))

[[ 1  3  7 12]
 [ 6 13 21 30]]


In [106]:
k = np.array([[1,2,4,5],[6,7,8,9]])
print(k.cumsum(axis = 0))

[[ 1  2  4  5]
 [ 7  9 12 14]]


DOT PRODUCT

In [107]:
x = np.array([[1,2,3,4],[5,6,7,8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [108]:
b = np.array([[0.5],[0.4],[0.6],[0.8]])
b

array([[0.5],
       [0.4],
       [0.6],
       [0.8]])

In [111]:
np.dot(x,b)

array([[ 6.3],
       [15.5]])

In [112]:
x@b

array([[ 6.3],
       [15.5]])

the datatype that will represent an data in a better way will be set in to the default data type.
like if we have used integer and float64 then the default datatype will be set to float64.

Indexing, Slicing

In [113]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [114]:
a[2]

np.int64(8)

In [115]:
a[2:5]

array([ 8, 27, 64])

In [116]:
a[0:6:2]

array([ 0,  8, 64])

In [117]:
a[ : :-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [118]:
a = np.arange(20).reshape(5,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [120]:
a[2,3]

np.int64(11)

In [ ]:
a[0:5,1] # return all the rows with the first column value.

array([ 1,  5,  9, 13, 17])

In [122]:
b = np.arange(20).reshape(5,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
b[1:3,3] #see this

array([ 7, 11])

Stacking arrays

In [126]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [127]:
b = np.arange(6,10).reshape(2,2)
b

array([[6, 7],
       [8, 9]])

In [128]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [135]:
np.hstack((a,b))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  6,  7],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,  8,  9]])

Splitting one array in to smaller ones

In [136]:
a = np.arange(0,24).reshape(2,12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [137]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [138]:
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])]

Broadcasting

Because of broadcasting we are able to perform vectorization operation.

3x3
3x1

if value is same or the value is 1 then broadcasting is possible

5x4
  4

if the size is same and where the dimensions are not present, it adds 1 automatically.
so in this case 4 will be changed to 1x4 and it will be compatible.

256x256x64
        64

in the case of a 3d array (shape of an array), if a 1d array has to be applied on it like in this case, then it can be broadcasted in this case.

it will preappend 1 automatically

**Adding a scalar value**

In [141]:
a = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
a+4

array([[5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

**adding a row vector to matrix**

In [142]:
a = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
b = np.array([0.4,0.6,0.7,0.8])
a+b

array([[1.4, 2.6, 3.7, 4.8],
       [1.4, 2.6, 3.7, 4.8],
       [1.4, 2.6, 3.7, 4.8]])

**broadcasting with a column vector**

In [143]:
a = np.array([[2]])
b = np.array([4])
a+b

array([[6]])

**Task 1**