The following notebook contains some practice exercises that can done for practicing the basics of numpy operations.

Question 1

In [1]:
import numpy as np

data1 = [1,3,9,12,18]
arr1 = np.array(data1)
arr1

array([ 1,  3,  9, 12, 18])

In [2]:
data2 = [[1,5,2,0],[3,6,4,7]]
arr2 = np.array(data2)
arr2

array([[1, 5, 2, 0],
       [3, 6, 4, 7]])

In [7]:
data3 = [['7','6'], ['5','4'], ['3','2']]
arr3 = np.array(data3)
arr3

array([['7', '6'],
       ['5', '4'],
       ['3', '2']], dtype='<U1')

In [9]:
data4 = [[11,52,20,50],[34,61,43,17]]
arr4 = np.array(data4)
arr4

array([[11, 52, 20, 50],
       [34, 61, 43, 17]])

Question 2

In [12]:
data1 + data2

[1, 3, 9, 12, 18, [1, 5, 2, 0], [3, 6, 4, 7]]

In [13]:
data1 * 10

[1,
 3,
 9,
 12,
 18,
 1,
 3,
 9,
 12,
 18,
 1,
 3,
 9,
 12,
 18,
 1,
 3,
 9,
 12,
 18,
 1,
 3,
 9,
 12,
 18,
 1,
 3,
 9,
 12,
 18,
 1,
 3,
 9,
 12,
 18,
 1,
 3,
 9,
 12,
 18,
 1,
 3,
 9,
 12,
 18,
 1,
 3,
 9,
 12,
 18]

In [16]:
arr1 = np.array(data1, dtype=int)
arr1

array([ 1,  3,  9, 12, 18])

In [ ]:
arr2 = np.array(data2, dtype=int)
arr2

In [ ]:
arr3 = np.array(data3, dtype=int)
arr3

In [ ]:
arr4 = np.array(data4, dtype=int)
arr4

Question 4

In [18]:
arr6 = np.zeros((3,5))
arr6

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
arr7 = np.ones((2,8))
arr7

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
arr8 = np.random.rand(6,3)
arr8

array([[0.35353337, 0.09526984, 0.77473038],
       [0.59076955, 0.69557036, 0.92717794],
       [0.75009509, 0.42053013, 0.20085075],
       [0.30666895, 0.72864022, 0.94925454],
       [0.02271989, 0.54693413, 0.2141576 ],
       [0.2088618 , 0.12907893, 0.3359515 ]])

Question 5

In [27]:
arr1[2:4] = arr1[2:4] ** 2
arr2[2:4] = arr2[2:4] ** 2


In [28]:
arr1

array([    1,     3,  6561, 20736,    18])

In [29]:
arr2

array([[1, 5, 2, 0],
       [3, 6, 4, 7]])

Question 6

In [32]:
import numpy as np

Subjects = np.array([
    ["ML", "OS", "CCN"],
    ["OS", "AI", "MP"],
    ["CCN", "ML", "AI"]
])


In [33]:
Subjects[(Subjects != "ML") & (Subjects != "AI")] = 0
Subjects


array([['ML', '0', '0'],
       ['0', 'AI', '0'],
       ['0', 'ML', 'AI']], dtype='<U3')

Question 7

In [37]:
arr1 = arr1.T
arr1

array([    1,     3,  6561, 20736,    18])

In [38]:
arr2 = arr2.T
arr2

array([[1, 3],
       [5, 6],
       [2, 4],
       [0, 7]])

In [39]:
arr3 = arr3.T
arr3

array([['7', '5', '3'],
       ['6', '4', '2']], dtype='<U1')

Question 8

In [44]:
np.concatenate([arr2, arr4], axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 4

In [ ]:
np.vstack((arr2,arr4))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 4

In [ ]:
np.hstack((arr2,arr4))

Question 9

In [50]:
col_mean = arr2.mean(axis=0)
data2_demeaned = arr2 - col_mean
data2_demeaned


array([[-1., -2.],
       [ 3.,  1.],
       [ 0., -1.],
       [-2.,  2.]])

Question 10

In [51]:
arr2 = arr2.reshape(4,2)
arr2

array([[1, 3],
       [5, 6],
       [2, 4],
       [0, 7]])

Question 11

In [52]:
import numpy as np

scores = np.array([
    [60, 70, 50],
    [40, 60, 80],
    [70, 55, 65]
])


In [53]:
max_scores = scores.max(axis=1)
max_scores

array([70, 80, 70])

Question 12

In [54]:
import numpy as np

marks = np.array([
    [60, 70, 50],   # Subject 1
    [40, 60, 80],   # Subject 2
    [70, 55, 65]    # Subject 3
])

credit_hours = np.array([2, 3, 4])


In [55]:
grade_points = np.where(marks >= 80, 4.0,
                np.where(marks >= 75, 3.4,
                np.where(marks >= 70, 3.0,
                np.where(marks >= 67, 2.7,
                np.where(marks >= 64, 2.4,
                np.where(marks >= 60, 2.0,
                np.where(marks >= 57, 1.7,
                np.where(marks >= 54, 1.4,
                np.where(marks >= 50, 1.0, 0.0)))))))))


In [56]:
weighted_gp = grade_points * credit_hours[:, np.newaxis]

In [57]:
total_credits = credit_hours.sum()
cgpa = weighted_gp.sum(axis=0) / total_credits
cgpa

array([1.77777778, 1.95555556, 2.62222222])

Question 13

In [64]:
unique_sorted_subjects = np.sort(np.unique(Subjects))
unique_sorted_subjects

array(['0', 'AI', 'ML'], dtype='<U3')

Question 14

In [65]:
import numpy as np

A = np.random.rand(4, 4)
print("Matrix A:\n", A)

dot_product = np.dot(A, A)
print("\nDot Product (A·A):\n", dot_product)

inverse_A = np.linalg.inv(A)
print("\nInverse of A:\n", inverse_A)

Matrix A:
 [[0.40239454 0.25983259 0.4739209  0.31581109]
 [0.8785391  0.76378458 0.15539829 0.22280859]
 [0.38738429 0.6169462  0.82564843 0.09890049]
 [0.66346015 0.62305709 0.64721575 0.45172909]]

Dot Product (A·A):
 [[0.78331205 0.79216338 0.82677069 0.37450566]
 [1.23255744 1.04633483 0.80755844 0.56364825]
 [1.08335245 1.14287037 1.02516718 0.38613443]
 [1.36477822 1.32902027 1.23798849 0.61641967]]

Inverse of A:
 [[ 7.44146715  2.48434045  0.36180057 -6.50702511]
 [-7.93253506 -0.89873896  0.03340515  5.98173908]
 [ 2.93893202 -0.24804809  1.31054536 -2.21923645]
 [-4.19901631 -2.05378534 -2.45514224  6.69983798]]


Question 15

In [66]:
import numpy as np

A = np.random.rand(4, 4)

dot_product = np.dot(A, A)

inverse_A = np.linalg.inv(A)

np.save("matrix_A.npy", A)
np.save("dot_product.npy", dot_product)
np.save("inverse_A.npy", inverse_A)

np.savez("all_arrays.npz", A=A, dot_product=dot_product, inverse_A=inverse_A)

print("Arrays saved to disk!")


Arrays saved to disk!
